package;

class Keys_text {
	static public var TITLE = "Title";
	static public var AGENT = "Agent";
	static public var MECHANIC = "Mechanic";
	static public var PROFESSOR = "Professor";
	static public var CLICK_TO_START = "click_to_start";
	static public var WORKPLACE = "Workplace";
	static public var ENCOURAGE = "Encourage";
	static public var INJECTION = "Injection";
	static public var BUILDWORKPLACE = "BuildWorkplace";
	static public var HIREWORKER_1 = "HireWorker_1";
	static public var HIREWORKER_2 = "HireWorker_2";
	static public var HIREWORKER_3 = "HireWorker_3";
	static public var ENCOURAGE_WONTWORK = "Encourage_WontWork";
	static public var INJECTION_WONTWORK = "Injection_WontWork";
	static public var BUILDWORKPLACE_WONTWORK = "BuildWorkplace_WontWork";
	static public var HIREWORKER_1_WONTWORK = "HireWorker_1_WontWork";
	static public var HIREWORKER_2_WONTWORK = "HireWorker_2_WontWork";
	static public var HIREWORKER_3_WONTWORK = "HireWorker_3_WontWork";
	static public var ENCOURAGE_USEITEM = "Encourage_UseItem";
	static public var INJECTION_USEITEM = "Injection_UseItem";
	static public var BUILDWORKPLACE_USEITEM = "BuildWorkplace_UseItem";
	static public var HIREWORKER_1_USEITEM = "HireWorker_1_UseItem";
	static public var HIREWORKER_2_USEITEM = "HireWorker_2_UseItem";
	static public var HIREWORKER_3_USEITEM = "HireWorker_3_UseItem";
	static public var PAUSEHAPPYCOUNT = "PauseHappyCount";
	static public var PAUSE_HAPPY_1 = "Pause_Happy_1";
	static public var PAUSE_HAPPY_2 = "Pause_Happy_2";
	static public var PAUSENORMALCOUNT = "PauseNormalCount";
	static public var PAUSE_NORMAL_1 = "Pause_Normal_1";
	static public var PAUSE_NORMAL_2 = "Pause_Normal_2";
	static public var PAUSEDRUGGEDCOUNT = "PauseDruggedCount";
	static public var PAUSE_DRUGGED_1 = "Pause_Drugged_1";
	static public var PAUSE_DRUGGED_2 = "Pause_Drugged_2";
	static public var PAUSEUNHAPPYCOUNT = "PauseUnhappyCount";
	static public var PAUSE_UNHAPPY_1 = "Pause_Unhappy_1";
	static public var PAUSE_UNHAPPY_2 = "Pause_Unhappy_2";
	static public var PAUSE_UNHAPPY_3 = "Pause_Unhappy_3";
	static public var BACK = "back";
	static public var WORKERNAMES = "WorkerNames";
}